version: '3.7'
services:    
  web:
    image: web-educonnect
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
      - "24678:24678"
